baseURL: "https://kevin.st-sauveur.net/"
languageCode: en-ca
title: "Kevin.St-Sauveur.net"
theme: "PaperMod"

menu:
    main:
        - name: Archive
          url: archives/
          weight: 10
        - name: "Posts"
          url: posts/
          weight: 10
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: "About"
          url: about/
          weight: 10

enableEmoji: true

minify:
    disableXML: true
    minifyOutput: true

assets:
    favicon: "/favicon.ico?v=2"
    favicon16x16: "/favicon-16x16.png?v=2"
    favicon32x32: "/favicon-32x32.png?v=2"
    apple_touch_icon: "/apple-touch-icon.png?v=2"
    safari_pinned_tab: "/safari-pinned-tab.svg?v=2"
    msapplication_TileColor: "#2b5797"
    theme_color: "#ffffff"

params:
    env: production
    GitHubUser: kevinstsauveur
    author: Kevin St-Sauveur
    description: "kevin.st-sauveur.net | https://github.com/kevinstsauveur/kevin.st-sauveur.ca"

    profileMode:
        enabled: true
        title: "Kevin St-Sauveur" # optional default will be site title
        subtitle: "Technology enthusiast"
        imageUrl: "/img/profile.jpg" # optional
        imageTitle: "Profile picture" # optional
        imageWidth: 300 # custom size
        imageHeight: 300 # custom size
        buttons:
            - name: Posts
              url: "/posts"
            - name: About
              url: "/about"

    socialIcons: # optional
        - name: github
          url: "https://github.com/kevinstsauveur/"
        - name: linkedin
          url: "https://www.linkedin.com/in/kevinstsauveur"
        - name: email
          url: "mailto:kevin@st-sauveur.ca"
        - name: RsS
          url: "index.xml"

    cover:
        linkFullImages: true

    ShowShareButtons: true
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowToc: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    defaultTheme: auto

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

    googleAnalytics: "G-6ZQP7T805G"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
    goldmark:
        renderer:
            unsafe: true
